version: '3'

x-haproxy-defaults: &haproxy-service
    image: 'haproxy:2.0-alpine'
    volumes:
        - './haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro'

x-keepalived-defaults: &keepalived-service
    image: 'osixia/keepalived:2.0.19'
    cap_add:
        - NET_ADMIN
        - NET_BROADCAST
        - NET_RAW
    environment:
        KEEPALIVED_COMMAND_LINE_ARGUMENTS: >-
            --log-detail
#      -–dont-release-vrrp
#      -–dont-release-ipvs
#      --log-detail
#      --dump-conf

networks:
    api:
        driver: bridge
    ha-stack:
        ipam:
            config:
                - subnet: 172.20.0.0/24
services:
    nginx:
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - './docker/rootfs/pictshare.conf:/etc/nginx/nginx.conf'
        depends_on:
            - pictshare
        networks:
            - api
    pictshare:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - './data:/var/www/data'
        environment:
            - URL=http://13.57.13.208/
        networks:
            - api
    keepalived-a:
        <<: *keepalived-service
        network_mode: host
        volumes:
            - './keepalived/proxy-a/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro'
            - './keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro'

    keepalived-b:
        <<: *keepalived-service
        network_mode: host
        volumes:
            - './keepalived/proxy-b/keepalived.conf:/usr/local/etc/keepalived/keepalived.conf:ro'
            - './keepalived/notify.sh:/container/service/keepalived/assets/notify.custom.sh:ro'

    haproxy-a:
        <<: *haproxy-service
        networks:
            ha-stack:
                ipv4_address: 172.20.0.50
                aliases:
                    - haproxy-a.ha.stack

    haproxy-b:
        <<: *haproxy-service
        networks:
            ha-stack:
                ipv4_address: 172.20.0.60
                aliases:
                    - haproxy-b.ha.stack
